In [4]:
#create 3*4 array with random value:
import numpy as np
d=np.random.random((3,4))
print("\nRandom Value\n",d)


Random Value
 [[0.57990183 0.87201664 0.23327632 0.77758569]
 [0.58421816 0.75182297 0.24906188 0.3006072 ]
 [0.94451871 0.59662172 0.01265641 0.55033511]]


In [6]:
#create 3*4 with zeros:
import numpy as np
c=np.zeros((3,4))
print("\n Array with all zeros\n",c)


 Array with all zeros
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
#1-d array with range 5-30 :
import numpy as np
e=np.arange(5,30,2)
print("\n Sequence array\n",e)


 Sequence array
 [ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [2]:
import numpy as np
ar=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(arr)
print"\nDimension of this array:",arr.ndim)
print("\nDatatype of this array:",arr.dtype)
print("\nShape:"arr.shape)
print("\Flatten array:"arr.flatten())


SyntaxError: unmatched ')' (3569437374.py, line 4)